name: survae_flows
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
- python=3.9
# Standard Libraries
- numpy>=1.19            # Numerical Linear Algebra
- scipy>=1.5             # Scientific Computing
- scikit-learn>0.23      # Machine Learning
# Plotting Libraries
- matplotlib>=3.3        # standard plotting library
- seaborn>=0.11          # Stats viz library
# GUI
- conda-forge::tqdm>=4.50              # 
- h5py
# Pytorch
- pytorch::pytorch
- pytorch::torchvision
- pytorch::torchaudio
- pytorch::cpuonly
# pip
- pip>=20.2
- pip:
    # pytorch lightning libraries
    - pytorch-lightning
    - lightning-bolts
    - pytorch_eo
    # Normalizing Flows Libraries
    - nflows
    - pyro-ppl
    - einops
    # personal directories
    - "git+https://github.com/VLL-HD/FrEIA.git"
    # Server/Logging
    - wandb
    - plotly
    # Formatters
    - black
    - pylint
    - isort
    - flake8
    - mypy
    - pytest
    # JupyterLab recognition
    - ipykernel
    - ipywidgets
    - pyprojroot
    # Plotting
    - corner
