name: survae_flows_gpu
channels:
- defaults
- pytorch
- conda-forge
dependencies:
- python=3.9
# Standard Libraries
- numpy>=1.19            # Numerical Linear Algebra
- scipy>=1.5             # Scientific Computing
- xarray>=0.16           # Data structures
- pandas>=1.1            # Data structure
- scikit-learn>0.23      # Machine Learning
- scikit-image>0.17      # Image Processing
# Plotting Libraries
- matplotlib>=3.3        # standard plotting library
- seaborn>=0.11          # Stats viz library
# GUI
- conda-forge::tqdm>=4.50              # 
# Earthy oackages
- conda-forge::rasterio>=1.1
# PYTORCH
- pytorch::pytorch           # tensor library
- pytorch::torchvision       # pytorch visual library
- pytorch::torchaudio
- pytorch::cudatoolkit=10.2
# pip
- pip>=20.2
- pip:
    # PYTORCH ECOSYSTEM
    - pyro-ppl        # probabilistic programming library
    - gpytorch        # Gaussian Processes
    - pytorch-lightning
    - lightning-bolts
    - lightning-flash
    - pytorch_eo
    - torchgeo
    # Normalizing Flows Libraries
    - nflows
    - pyro-ppl
    - einops
    # Server/Logging
    - wandb
    # Formatters
    - black
    - pylint
    - isort
    - flake8
    - mypy
    - pytest
    # JupyterLab recognition
    - ipykernel
    - ipywidgets
    - pyprojroot
    # Plots
    - corner
